name: Latest Blog Posts Workflow

on:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts from zyekh.com
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Fetch and Inject RSS Posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://zyekh.com/feed.xml"
          max_post_count: 5
          template: "$newline- [$title]($url)"
